In [666]:
print("Hello World")

Hello World

#Task       

1. Load your csv's into this notebook   
2. clean the files  
3. Output them      

Stretch:
1. Add some data engineering metrics you want to track.
2. Output the files to a local SSMS database with the data engineering metrics  
3. Ask Nirosh

In [667]:
import pandas as pd 

df = pd.read_csv("03_Library Systembook.csv")   
df

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
...,...,...,...,...,...,...
109,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,NaN,NaN,NaN

In [668]:
    #Cleanse Book titles
    df["Books"] = df["Books"].str.title()

In [669]:
df["Books"]

0                           Catcher In The Rye
1              Lord Of The Rings The Two Towers
2      Lord Of The Rings The Return Of The Kind
3                                    The Hobbit
4                                         Dune
                         ...
109                                         NaN
110                                         NaN
111                                         NaN
112                                         NaN
113                                         NaN
Name: Books, Length: 114, dtype: object

In [670]:
    #remove null values
    df = df.dropna(subset=["Books"])

In [671]:
df["Books"]

0                          Catcher In The Rye
1             Lord Of The Rings The Two Towers
2     Lord Of The Rings The Return Of The Kind
3                                   The Hobbit
4                                        Dune
5                                 Little Women
6                                           It
7                                      Misery
8                                     Catch 22
9                                 Animal Farm
10                                        1984
11                                Little Women
12                                East Of Eden
13                     America Is In The Heart
14                           Wuthering Heights
15                                  Dark Tales
16                          The Bloody Chamber
17                              Les Miserables
18                                     Dracula
19                                Frankenstein
Name: Books, dtype: object

In [672]:
df.isna().sum()

Id                        0
Books                     0
Book checkout             0
Book Returned             0
Days allowed to borrow    0
Customer ID               0
dtype: int64

In [673]:
df

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher In The Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord Of The Rings The Two Towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord Of The Rings The Return Of The Kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The Hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,It,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East Of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is In The Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0

In [674]:
#cleans date data remove "" and change datatype to datetime
df["Book checkout"] = df["Book checkout"].replace({'"': ''}, regex=True)   
df["Book checkout"] = pd.to_datetime(df["Book checkout"], errors="coerce")   
df["Book Returned"] = pd.to_datetime(df["Book Returned"], errors="coerce")

C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1329885204.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Book checkout"] = df["Book checkout"].replace({'"': ''}, regex=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1329885204.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Book checkout"] = pd.to_datetime(df["Book checkout"], errors="coerce")
C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1329885204.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Book checkout"] = pd.to_datetime(df["Book checkout"], errors="coerce")
C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1329885204.py:4: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Book Returned"] = pd.to_datetime(df["Book Returned"], errors="coerce")
C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1329885204.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Book Returned"] = pd.to_datetime(df["Book Returned"], errors="coerce")

In [675]:
df

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher In The Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord Of The Rings The Two Towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord Of The Rings The Return Of The Kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The Hobbit,2023-04-02,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0
5,6.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0
6,7.0,It,2063-04-10,2023-04-03,2 weeks,6.0
7,8.0,Misery,2023-04-15,2023-04-03,2 weeks,7.0
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0
10,11.0,1984,2023-04-23,2023-04-27,2 weeks,8.0
11,12.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0
12,13.0,East Of Eden,2023-04-30,2023-05-05,2 weeks,2.0
13,14.0,America Is In The Heart,2023-05-01,2023-05-07,2 weeks,3.0
14,15.0,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9.0
15,16.0,Dark Tales,2023-05-15,2023-06-01,2 weeks,2.0
16,17.0,The Bloody Chamber,NaT,2023-06-04,2 weeks,3.0
17,18.0,Les Miserables,2023-06-03,2023-06-07,2 weeks,5.0
18,19.0,Dracula,2023-06-10,2023-07-10,2 weeks,10.0
19,20.0,Frankenstein,2023-06-01,2023-06-20,2 weeks,2.0

In [676]:
df

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher In The Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord Of The Rings The Two Towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord Of The Rings The Return Of The Kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The Hobbit,2023-04-02,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0
5,6.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0
6,7.0,It,2063-04-10,2023-04-03,2 weeks,6.0
7,8.0,Misery,2023-04-15,2023-04-03,2 weeks,7.0
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0
10,11.0,1984,2023-04-23,2023-04-27,2 weeks,8.0
11,12.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0
12,13.0,East Of Eden,2023-04-30,2023-05-05,2 weeks,2.0
13,14.0,America Is In The Heart,2023-05-01,2023-05-07,2 weeks,3.0
14,15.0,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9.0
15,16.0,Dark Tales,2023-05-15,2023-06-01,2 weeks,2.0
16,17.0,The Bloody Chamber,NaT,2023-06-04,2 weeks,3.0
17,18.0,Les Miserables,2023-06-03,2023-06-07,2 weeks,5.0
18,19.0,Dracula,2023-06-10,2023-07-10,2 weeks,10.0
19,20.0,Frankenstein,2023-06-01,2023-06-20,2 weeks,2.0

In [677]:
df.isna().sum()

Id                        0
Books                     0
Book checkout             1
Book Returned             0
Days allowed to borrow    0
Customer ID               0
dtype: int64

In [678]:
df1 = pd.read_csv("03_Library SystemCustomers.csv")   
df1

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [679]:
#remove null values from dataset    
df1 = df1.dropna()
print(df1)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [680]:
df.dtypes

Id                               float64
Books                             object
Book checkout             datetime64[ns]
Book Returned             datetime64[ns]
Days allowed to borrow            object
Customer ID                      float64
dtype: object

In [681]:
df.dtypes

Id                               float64
Books                             object
Book checkout             datetime64[ns]
Book Returned             datetime64[ns]
Days allowed to borrow            object
Customer ID                      float64
dtype: object

In [682]:
df1.dtypes

Customer ID      float64
Customer Name     object
dtype: object

In [683]:
#create column showing date book is to be returned and changing datatype to datetime
df["Book Due Back"] = df["Book checkout"] + pd.Timedelta(days=14)
df["Book Due Back"] = pd.to_datetime(df["Book Due Back"], errors="coerce")

C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1000296922.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Book Due Back"] = df["Book checkout"] + pd.Timedelta(days=14)
C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\1000296922.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Book Due Back"] = pd.to_datetime(df["Book Due Back"], errors="coerce")

In [684]:
df.dtypes

Id                               float64
Books                             object
Book checkout             datetime64[ns]
Book Returned             datetime64[ns]
Days allowed to borrow            object
Customer ID                      float64
Book Due Back             datetime64[ns]
dtype: object

In [685]:
df["Overdue"] = df["Book Returned"] > df["Book Due Back"]

C:\Users\Admin\AppData\Local\Temp\ipykernel_6072\3973816948.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Overdue"] = df["Book Returned"] > df["Book Due Back"]

In [686]:
df

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book Due Back,Overdue
0,1.0,Catcher In The Rye,2023-02-20,2023-02-25,2 weeks,1.0,2023-03-06,False
1,2.0,Lord Of The Rings The Two Towers,2023-03-24,2023-03-21,2 weeks,2.0,2023-04-07,False
2,3.0,Lord Of The Rings The Return Of The Kind,2023-03-29,2023-03-25,2 weeks,3.0,2023-04-12,False
3,4.0,The Hobbit,2023-04-02,2023-03-25,2 weeks,4.0,2023-04-16,False
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0,2023-04-16,False
5,6.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0,2023-04-16,True
6,7.0,It,2063-04-10,2023-04-03,2 weeks,6.0,2063-04-24,False
7,8.0,Misery,2023-04-15,2023-04-03,2 weeks,7.0,2023-04-29,False
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0,2023-04-29,False
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0,2023-05-04,False
10,11.0,1984,2023-04-23,2023-04-27,2 weeks,8.0,2023-05-07,False
11,12.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0,2023-04-16,True
12,13.0,East Of Eden,2023-04-30,2023-05-05,2 weeks,2.0,2023-05-14,False
13,14.0,America Is In The Heart,2023-05-01,2023-05-07,2 weeks,3.0,2023-05-15,False
14,15.0,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9.0,2023-05-15,False
15,16.0,Dark Tales,2023-05-15,2023-06-01,2 weeks,2.0,2023-05-29,True
16,17.0,The Bloody Chamber,NaT,2023-06-04,2 weeks,3.0,NaT,False
17,18.0,Les Miserables,2023-06-03,2023-06-07,2 weeks,5.0,2023-06-17,False
18,19.0,Dracula,2023-06-10,2023-07-10,2 weeks,10.0,2023-06-24,True
19,20.0,Frankenstein,2023-06-01,2023-06-20,2 weeks,2.0,2023-06-15,True

In [687]:
df1

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [688]:
df.dtypes

Id                               float64
Books                             object
Book checkout             datetime64[ns]
Book Returned             datetime64[ns]
Days allowed to borrow            object
Customer ID                      float64
Book Due Back             datetime64[ns]
Overdue                             bool
dtype: object

In [689]:
# Creating and using a function to enrich the data by adding in the time a book was on loan.
data_enriched = df.copy()

def enrich_dateDuration(colA, colB, df=data_enriched):
    """
    Takes the two input columns and the dataframe to create a new column date_delta which is the difference, in days, between colA and colB.
    
    Note: ColA should be the highest of the expected date columns.
    """
    df['date_delta'] = (df[colA]-df[colB]).dt.days
    return df.head()

enrich_dateDuration(df=data_enriched, colA='Book Returned', colB='Book checkout')

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book Due Back,Overdue,date_delta
0,1.0,Catcher In The Rye,2023-02-20,2023-02-25,2 weeks,1.0,2023-03-06,False,5.0
1,2.0,Lord Of The Rings The Two Towers,2023-03-24,2023-03-21,2 weeks,2.0,2023-04-07,False,-3.0
2,3.0,Lord Of The Rings The Return Of The Kind,2023-03-29,2023-03-25,2 weeks,3.0,2023-04-12,False,-4.0
3,4.0,The Hobbit,2023-04-02,2023-03-25,2 weeks,4.0,2023-04-16,False,-8.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0,2023-04-16,False,-8.0

In [690]:
data_enriched = df.copy()
data_enriched['Days Between'] = (data_enriched['Book Returned'] - data_enriched['Book checkout']).dt.days
data_enriched.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book Due Back,Overdue,Days Between
0,1.0,Catcher In The Rye,2023-02-20,2023-02-25,2 weeks,1.0,2023-03-06,False,5.0
1,2.0,Lord Of The Rings The Two Towers,2023-03-24,2023-03-21,2 weeks,2.0,2023-04-07,False,-3.0
2,3.0,Lord Of The Rings The Return Of The Kind,2023-03-29,2023-03-25,2 weeks,3.0,2023-04-12,False,-4.0
3,4.0,The Hobbit,2023-04-02,2023-03-25,2 weeks,4.0,2023-04-16,False,-8.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0,2023-04-16,False,-8.0

In [691]:
# def myFunction(df): 
 #   def days_between(checkout, returned):  
 #       try:    
 #           d1 = pd.to_datetime(checkout, errors="coerce")  
 #           d2 = pd.to_datetime(returned, errors="coerce")
            
 #           if pd.isna(d1) or pd.isna(d2):  
 #               return None

 #           return(d2 -d1).days 
 #       except Exception:   
 #           return None 
        
 #   df["Days Between"] = df.apply(  
 #       lambda row: days_between(row["Book checkout"], row["Book Returned"]),
 #       axis=1
 #   )   

#    return df

In [692]:
df1.dtypes

Customer ID      float64
Customer Name     object
dtype: object

In [693]:
data_enriched.to_csv("Cleaned_03_Library Systembook.csv", index=False)

In [694]:
df1.to_csv("Cleaned_03_Library SystemCustomers.csv", index=False)